version: '3.4'

networks:
  ros:
    driver: bridge

services:
  roboticmosaic:
    image: roboticmosaic
    build:
      context: .
      dockerfile: ./Dockerfile
  
  ros-master:
    image: roboticmosaic
    command: roscore
    networks: 
      - ros
    restart: always

  ros-bridge-server:
    image: roboticmosaic
    depends_on: 
      - ros-master
    command: roslaunch rosbridge_server rosbridge_websocket.launch
    networks: 
      - ros
    restart: always

  talker:
    image: roboticmosaic
    depends_on:
      - ros-master
    command: rostopic pub /chatter std_msgs/String "hello" -r 1
    networks:
      - ros
    restart: always

  listener:
    image: roboticmosaic
    depends_on:
      - ros-master
    command: rostopic echo /chatter
    networks:
      - ros
    restart: always