version: '3.4'

networks:
  ros:
    driver: bridge

services:
  ros_melodic:
    image: ros_melodic
    build:
      context: .
      dockerfile: ./Dockerfile
  
  ros-master:
    image: ros_melodic
    command: roscore
    networks: 
      - ros
    restart: always

  publisher:
    image: ros_melodic
    depends_on:
      - ros-master
    command: rostopic pub /chatter std_msgs/String "hello" -r 1
    networks:
      - ros
    restart: always

  subscriber:
    image: ros_melodic
    depends_on:
      - ros-master
    command: rostopic echo /chatter
    networks:
      - ros
    restart: always

  ros-bridge-server:
    image: ros_melodic
    depends_on: 
      - ros-master
    command: roslaunch rosbridge_server rosbridge_websocket.launch
    networks: 
      - ros
    restart: always
