networks:
  x11:

services:
  ros-master:
    image: osrf/ros:melodic-desktop-full
    container_name: ros-master
    ports:
      - "11311:11311"
    command: stdbuf -o L roscore
    restart: always
    networks:
      - x11

  novnc:  
    image: theasp/novnc:latest
    environment: 
      - DISPLAY_WIDTH=1400
      - DISPLAY_HEIGHT=800
    ports:
      - "8080:8080"
    networks:
      - x11

  rviz:
    image: osrf/ros:melodic-desktop-full
    container_name: rviz
    environment: 
      - ROS_MASTER_URI=http://ros-master:11311
      - ROS_HOSTNAME=rviz
      - DISPLAY=novnc:0.0
    depends_on:
      - novnc
    command: 
      - rviz
    restart: always
    networks:
      - x11
