version: '2'

networks:
  ros:
    driver: bridge

services:
  ros-master:
    image: ros_melodic:base
    command: stdbuf -o L roscore
    networks:
      - ros
    restart: always

  publisher:
    image: ros_melodic:base
    depends_on:
      - ros-master
    environment:
      - "ROS_MASTER_URI=http://ros-master:11311"
      - "ROS_HOSTNAME=publisher"
    command: rostopic pub /chatter std_msgs/String "hello" -r 1
    networks:
      - ros
    restart: always

  subscriber:
    image: ros_melodic:base
    depends_on:
      - ros-master
    environment:
      - "ROS_MASTER_URI=http://ros-master:11311"
      - "ROS_HOSTNAME=subscriber"
    command: rostopic echo /chatter
    networks:
      - ros
    restart: always